### PR TITLE
Major update to new stable branch (1.4.0p10)

### PR DESCRIPTION
**Pull request by mcgege**
- Major update to check_mk 1.4.0p7
- Set password for **cmkadmin** to omd (default is random password)
- Howto update in README

_Maybe you should tag the existing code with 1.2.8p23 before merging this patch or merge this into a new 1.4 branch?_

### CODE REVIEW

**Comment by mcgege** [comment]
@viper0131 Are you still interested in maintaining this repository? If not, I could help out ...

**Comment by viper0131** [comment]
Hello Michael,

Of course you are welcome to help. I'm currently busy with other projects. 

I believed I added you as contributor. 

Gr,
Machiel

Verstuurd vanaf mijn iPhone

**Comment by mcgege** [comment]
@viper0131 Hi Machiel, I think I need "collaborator" rights, otherwise I cannot help you maintain the repository ...

**Comment by viper0131** [comment]
Hi Michael,

added you as Collaborator a few minutes ago.

Have fun,
Machiel

**Comment by mcgege** [comment]
@viper0131 Thanks! I'll merge & recheck this in two weeks after my holiday :-)

**Pull request merged**
